### ISSUE TITLE
Threaded 

### ISSUE THREAD

**Issue by unnaturalistic** [Bonnie39/tominecon_cracker#1]
Probably make it threaded and make it run multiple threads, also make it so you can choose the amount of threads, for now that should be good

**Comment by Bonnie39** [comment]
https://github.com/Bonnie39/tominecon_cracker/releases/tag/1.1

As suggested, you can now run tominecon.7z cracker on multiple threads, and can specify the number of threads to use.
The number of threads will default to 1 if no amount it specified

**Comment by Bonnie39** [comment]
i guess i can close this issue now lol
